var Events = cc.Class.extend({
});

Events.GAMEMODEL_START_GAME = 100;
Events.GAMEMODEL_COUNT_DOWN_TIME_CHANGED = 101;
Events.GAMEMODEL_SHOW_QUESTION = 102;
Events.GAMEMODEL_REMAIN_TIME_CHANGED = 103;
Events.GAMEMODEL_SHOW_ANSWER = 104;
Events.GAMEMODEL_SHOW_SCORE = 105;
Events.GAMEMODEL_GET_TOPIC_LIST_SUCCESS = 106;
Events.GAMEMODEL_CHOOSE_ANSWER_FAILED = 107;


Events.OPEN_TOPIC_LIST_SCENE = 200;
Events.CHANGE_LEVEL_TOPIC_LIST_SCENE = 201;


Events.SHARE_FACEBOOK = 300;
Events.SHARE_SCORE_FACEBOOK = 301;


Events.OPEN_MAIN_MENU_SCENE = 400;


Events.OPEN_GAME_SCENE = 500;
Events.CHOOSE_ANSWER_GAME_SCENE = 501;
Events.MUSIC_ANSWER_GAME_SCENE = 502;
Events.PLAY_MUSIC_QUESTION_GAME_SCENE = 503;