var res = {
    TOPIC_LIST_JSON: "res/data/topicList.json",
    N1_PNG: "res/1.png",
    N2_PNG: "res/2.png",
    N3_PNG: "res/3.png",
    GO_PNG: "res/go.png",
    ADS_PNG: "res/ads.png",
    LIGHT_PNG: "res/light.png",
    STATE_PNG: "res/stage.png",
    BG_BOTTOM_BANNER_PNG: "res/bg-bottom-banner.png",
    ANSWER_BG_SELECTED_PNG: "res/answer-bg-selected.png",
    ANSWER_BG_PNG: "res/answer-bg.png",
    TIME_BG_PNG: "res/time-bg.png",
    EFFECT_TIME_PNG: "res/effect-time.png",
    QUESTION_BG_PNG: "res/question-bg.png",
    LOGO_PNG: "res/logo.png",
    BACK_SELECT_PNG: "res/back-select.png",
    BACK_PNG: "res/back.png",
    BTN_LEVEL_QUEST_PNG: "res/button-level-question.png",
    BTN_LEVEL_QUEST_SELECT_PNG: "res/button-level-question-select.png",
    BG_MENU_JPG: "res/bg-menu.jpg",
    BG_MENU_PNG: "res/bg-menu.png",
    BTN_PLAY_SELECT_PNG: "res/btn-play-select.png",
    BTN_PLAY_PNG: "res/btn-play.png",
    BTN_SHARE_FB_SELECT_PNG: "res/btn-share-fb-select.png",
    BTN_SHARE_FB_PNG: "res/btn-share-fb.png",
    SCROLLBARBG_PNG: "res/scrollBg-h.png",
    THUMRSCROLL_PNG: "res/scrollButton-h.png",
    BGNAV_PNG: "res/bgNav.png",
    BGNAV_SELECT_PNG: "res/bgNav-select.png",
    CHOOSE_LEVEL_TOPIC_PNG: "res/topic-choose.png",
    BG_SCORE_PNG: "res/bg-score.png",
    BTN_REPLAY_PNG: "res/replay.png",
    BTN_REPLAY_SELECT_PNG: "res/replay-select.png",
    BTN_SHARE_FB2_PNG: "res/share_fb.png",
    BTN_SHARE_FB2_SELECT_PNG: "res/share_fb_select.png",
    MUISC_BG: "res/sounds/background.mp3",
    DOREMON_PNG: "res/doremon.png",
    DOREMON_SE_PNG: "res/doremon-se.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}