var Events = cc.Class.extend({
});

Events.GAMEMODEL_START_GAME = 100;
Events.GAMEMODEL_SHOW_QUESTION = 101;
Events.GAMEMODEL_REMAIN_TIME_CHANGED = 102;
Events.GAMEMODEL_SHOW_ANSWER = 103;
Events.GAMEMODEL_GAME_OVER = 104;
Events.GAMEMODEL_USE_HELP = 105;
Events.GAMEMODEL_STOP_GAME = 106;
Events.GAMEMODEL_CONTINUE_GAME = 107;
Events.GAMEMODEL_WIN_GAME = 108;
Events.GAMEMODEL_USE_HELP_TEXT = 109;

Events.GAMESCENE_REPLAY_CLICK = 200;
Events.GAMESCENE_HELP_CLICK = 201;
Events.GAMESCENE_NEXT_STAGE_CLICK = 202;
Events.GAMESCENE_ANSWER_CLICK = 203;
Events.GAMESCENE_TEXT_HELP_CLICK = 204;

Events.STARTSCENE_PLAY_CLICK = 300;
Events.STARTSCENE_GET_RANK_SUCCESS = 301;
Events.GAMESCENE_GET_RANK_SUCCESS = 302;
Events.BACKSTART_SCENE = 303;

Events.BUTTON_CLICK = 400;
Events.USE_HELP = 401;
Events.LOSE_GAME = 402;
Events.GAME_COUNTDOWN = 403;
Events.WIN_GAME = 404;
Events.VOLUME_OFF = 405;
Events.VOLUME_ON = 406;
Events.STOP_EFFECT = 407;